apiVersion: garden.io/v0
kind: Deploy
type: kubernetes
name: demo-api
description: Apply the demo API workload through Kustomize.
dependencies:
  - deploy.platform
source:
  path: .
include:
  - k8s/apps/workloads/demo-api/**
spec:
  kustomize:
    path: k8s/apps/workloads/demo-api/overlays/local
    version: 5
