apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: demo-api-app
    files:
      - demo_api.py

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: demo-api
    app.kubernetes.io/part-of: homelab-garden
    homelab-garden.io/layer: app

