apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    app.kubernetes.io/part-of: homelab-garden
    homelab-garden.io/layer: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    app.kubernetes.io/part-of: homelab-garden
    homelab-garden.io/layer: app
