apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-hcloud-lab
  namespace: argocd
  labels:
    app.kubernetes.io/name: app-of-apps-hcloud-lab
    app.kubernetes.io/part-of: homelab-garden
spec:
  project: hcloud-lab
  source:
    repoURL: https://github.com/erauner12/homelab-garden.git
    targetRevision: main
    path: gitops/applications-hcloud-lab
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  revisionHistoryLimit: 3
