apiVersion: v1
kind: Secret
metadata:
    name: homelab-garden-local-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    type: ENC[AES256_GCM,data:GPN7,iv:0tK+7AW4jyaS9Jmc6XCnB+w2Uhbw2DsanXl7cZpmclY=,tag:5UsSNA8AYIeSNNT3Mcy0Vg==,type:str]
    url: ENC[AES256_GCM,data:IdIS3i56EmnfBKCnSLUHP+/RlJEG+OdF6B1/aXTEjJdAjF42/Qqd1sy+eSMbESY=,iv:3AsgjIkOsWgsD8lYrtdC5zr54g888TAzWRLJWp+3zgY=,tag:Tec0OrfdzQRCoRKn2zAwdA==,type:str]
    username: ENC[AES256_GCM,data:Lyf4IDuZK/rl,iv:TrLVHQPyGmPGbpaBhx2Z2SRbPfHtLcrLGULCQC1Yjlw=,tag:UeicTzICBwTyW/9W7xwXgA==,type:str]
    password: ENC[AES256_GCM,data:j41/kbtsMIhCD8j3Tfd1yYso82N0yF1qK2MF87RBIHqlCP1XXEcvtw==,iv:wOGlIl4yXFIvrfjIHj/VQyyH93fo5bvoOD+EV7zgklQ=,tag:mzqqu9Yd85W5NdYzJPirIQ==,type:str]
sops:
    age:
        - recipient: age1sfjw5p0cvyu3s972gt5hrdjzjve9r032rl2p0ntlqqs9h74e2guq5lpt68
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdG04NW9WUDJJRE40NU9W
            aXk2cERGRGJPSTkxWHBLTk5rbXRjSGJmSkdRCnR0YVJJQWNxNC9XdEs3NE1XK3Bk
            NVlBMG5obkZTYlNFYlJOOEw2cE0zU2MKLS0tIEtNSi9jQ2wveUhGeEZxNHpQYk1R
            T1l6Q1ZNOG5hWVB0aFRzNDdRTDJFVm8KJn99itoNDjwigOPBQ8nRe97g1Qcgaros
            Gniy+IKPapC46RhPDv388fcqrWYFOx4trMOc2WAAQN67LL3+wrdGhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T16:23:14Z"
    mac: ENC[AES256_GCM,data:Eb44Csc+kxIeJJawU3GM6kMWb/0Udlg9j9sQFnBYG4GRCcJO5fWnSCOKE2+LmZhLfCoDsuJxNMLufvypWsIEUpdVjloA49Q2qqKScsUSQIpTkH59JOXkvsR0LlngOa8vbJJ45/Zpr6VaDLynGcEml2XpW1LuaX8RJxaDTsYJjis=,iv:3BRYuA98Qro87Pi12J/C82hk25o6Dag2tKMXCIgZ3Js=,tag:wp07YYpmMWYDs49nkCVbUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
