apiVersion: v1
kind: Secret
metadata:
    name: hcloud-lab
    namespace: default
type: Opaque
stringData:
    HCLOUD_TOKEN: ENC[AES256_GCM,data:d3TPKPqVkIWrxNVj90n63BTqgGvF8rXv7nbQi5ZCyYix9IDBn3zznz94g+YyJOI1tzGSLBai8Da74CDPj+FNgA==,iv:nBe18ArJAzC6WvvWa7JJCgebJdULz2XW9PYo1f+Mlg8=,tag:kl84/PV/RGpz6kIvMgUFEA==,type:str]
sops:
    age:
        - recipient: age1sfjw5p0cvyu3s972gt5hrdjzjve9r032rl2p0ntlqqs9h74e2guq5lpt68
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVitucnBlNkVUOGpRbVhI
            TDYzTWlZQ0J6Sk1hN3Ewb0pEWDNJU3BtQVg4CjVibEduY2tHeTlkYWZ0c1haYytM
            UGJCM2RqR0E5NXFJZmd2VE1RWWdQSE0KLS0tIHhkK0NSY3krenEzbVQyQW5HOGIw
            VmNHTWFnMlVHckIzY1FPNnRIRFUyeEUKFRubXEWonDwZn2s/+Ci9G9yw3wUqa09h
            bBJsUhINI+M9ACpolpC5bMYu4nC0azBa38IMYGenaTi9Qva2zo5WEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T22:38:43Z"
    mac: ENC[AES256_GCM,data:pg4Ge4cs736TuL9za9I20jZiam2QMi14zrQtUG6+O5DDCqRQis74BlnJXjWULTUY/cfJcEOPN+gXhFad2EgbXgjwhXJjqTlOxrJypFlYaMHYgW8TphO5iVdgxC3FB+3XPWE5T+ah6ntH5Qhc67eeiOY70b8esdGiZSDBofEHLBk=,iv:t7teLvi8nmterW5iFWvijlfM6Dqys5CWbkBBLC6+rc0=,tag:vQaxuxd3++FOsZx3UjVdLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
